version: '3'
services:
  app:
    image: paigehai/2048game:latest
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf