version: '3'
services:
  app:
    image: paigehai/2048game:latest
    ports:
      - "8070:80"
  nginx:
    image: nginx
    ports:
      - "8060:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf