version: '3'
services:
  app:
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - "8070:80"

  nginx:
    image: nginx
    ports:
      - "8070:80"
    volumes:
      - /Users/paigehai/.jenkins/workspace/Pipeline/nginx.conf:/etc/nginx/nginx.conf
      - /Users/paigehai/.jenkins/workspace/Pipeline/src:/src
